spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product
          uri: http://localhost:8801
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationFilter
              args:
                postOnly: true
#            - name: RoleAuthorizationFilter
#              args:
#                allowedRoles: "ADMIN"
        - id: user
          uri: http://localhost:8802
          predicates:
            - Path=/api/v2/**
        - id: auth
          uri: http://localhost:8804
          predicates:
            - Path=/**

